version: '3'

services:
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    volumes:
      - data-volume:/var/lib/db
    ports:
      - 25432:5432

  django:
    build: .
    # TODO - Must fix. Having to disable reload to use ipdb.
    # to get a container up and working with ipdb
    # docker-compose run --rm --service-ports django
    # command: python3 manage.py runserver 0.0.0.0:8000 --noreload
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=settings.local
    restart: unless-stopped
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  rabbit:
    image: rabbitmq:3.8.5-management
    restart: unless-stopped
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: "SECRET_COOKIE"
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    ports:
      - "15673:15672"
      - "9672:5672"


volumes:
  data-volume:
  rabbit-data:
